PRAGMA foreign_keys = ON;

INSERT INTO User VALUES(1,'up201706736@fe.up.pt','lp');
INSERT INTO User VALUES(2,'up201705373@fe.up.pt','dhero');
INSERT INTO User VALUES(3,'up201706534@fe.up.pt','b670');

INSERT INTO Country (id,name) VALUES(1,"United States of America");
INSERT INTO Country (id,name) VALUES(2,"Portugal");
INSERT INTO Country (id,name) VALUES(3,"Australia");
INSERT INTO Country (id,name) VALUES(4,"Italy");
INSERT INTO Country (id,name) VALUES(5,"England");
INSERT INTO Country (id,name) VALUES(6,"Scotland");
INSERT INTO Country (id,name) VALUES(7,"Germany");
INSERT INTO Country (id,name) VALUES(8,"Brazil");
INSERT INTO Country (id,name) VALUES(9,"Mexico");
INSERT INTO Country (id,name) VALUES(10,"France");
INSERT INTO Country (id,name) VALUES(11,"Canada");
INSERT INTO Country (id,name) VALUES(12,"Japan");
INSERT INTO Country (id,name) VALUES(13,"Angola");
INSERT INTO Country (id,name) VALUES(14,"Belgium");
INSERT INTO Country (id,name) VALUES(15,"South Africa");
INSERT INTO Country (id,name) VALUES(16,"Venezuela");
INSERT INTO Country (id,name) VALUES(17,"Egypt");
INSERT INTO Country (id,name) VALUES(18,"Jamaica");
INSERT INTO Country (id,name) VALUES(19,"Kazakhstan");
INSERT INTO Country (id,name) VALUES(20,"Spain");

INSERT INTO Gender VALUES(1,'Female');
INSERT INTO Gender VALUES(2,'Male');

INSERT INTO Role VALUES(1,'Actor');
INSERT INTO Role VALUES(2,'Director');
INSERT INTO Role VALUES(3,'Writer');

INSERT INTO Genre VALUES(1,'Crime','Films of this genre generally involve various aspects of crime and its detection.');
INSERT INTO Genre VALUES(2,'Drama','In film and television, drama is a genre of narrative fiction (or semi-fiction) intended to be more serious than humorous in tone.');
INSERT INTO Genre VALUES(3,'Science-fiction','Genre that uses speculative, fictional science-based depictions of phenomena that are not fully accepted by mainstream science.');
INSERT INTO Genre VALUES(4,'Comedy','Comedy is a genre of film in which the main emphasis is on humour.');
INSERT INTO Genre VALUES(5,'Horror','A horror film is a film that seeks to elicit fear.');

INSERT INTO Person VALUES(1,'Martin','Scorsese',NULL,NULL,'1942-11-17',NULL,1,2);
INSERT INTO Person VALUES(2,'Paul','Schrader',NULL,NULL,'1946-07-22',NULL,1,2);
INSERT INTO Person VALUES(3,'Robert','De Niro',NULL,NULL,'1943-08-17',NULL,1,2);
INSERT INTO Person VALUES(4,'Jodie','Foster',NULL,NULL,'1962-11-19',NULL,1,1);
INSERT INTO Person VALUES(5,'Uma','Thurman',NULL,NULL,'1970-04-29',NULL,1,1);
INSERT INTO Person VALUES(6,'Samuel','L. Jackson',NULL,NULL,'1948-12-21',NULL,1,2);
INSERT INTO Person VALUES(7,'John','Travolta',NULL,NULL,'1954-02-18',NULL,1,2);
INSERT INTO Person VALUES(8,'Maria','Medeiros',NULL,NULL,'1965-08-19',NULL,2,1);
INSERT INTO Person VALUES(9,'Quentin','Tarantino',NULL,NULL,'1963-03-27',NULL,1,2);
INSERT INTO Person VALUES(10,'Vince','Gilligan',NULL,NULL,'1967-02-10',NULL,1,2);
INSERT INTO Person VALUES(11,'Bryan','Cranston',NULL,NULL,'1956-03-07',NULL,1,2);
INSERT INTO Person VALUES(12,'Aaron','Paul',NULL,NULL,'1979-08-27',NULL,1,2);
INSERT INTO Person VALUES(13,'Anna','Gunn',NULL,NULL,'1968-08-11',NULL,1,1);
INSERT INTO Person VALUES(14,'Stanley','Kubrick',NULL,NULL,'1928-07-26','1999-03-07',1,2);
INSERT INTO Person VALUES(15,'Malcolm','McDowell',NULL,NULL,'1943-06-13',NULL,5,2);
INSERT INTO Person VALUES(16,'Ewan','McGregor',NULL,NULL,'1971-03-31',NULL,6,2);
INSERT INTO Person VALUES(17,'Jeff','Bridges',NULL,NULL,'1949-12-04',NULL,1,2);
INSERT INTO Person VALUES(18,'Steve','Buscemi',NULL,NULL,'1957-12-13',NULL,1,2);
INSERT INTO Person VALUES(19,'Joel','Coen',NULL,NULL,'1954-11-29',NULL,1,2);
INSERT INTO Person VALUES(20,'Jack','Nicholson',NULL,NULL,'1937-04-22',NULL,1,2);
INSERT INTO Person VALUES(21,'Shelley','Duvall',NULL,NULL,'1949-07-07',NULL,1,1);
INSERT INTO Person VALUES(22,'Bob','Odenkirk',NULL,NULL,'1962-10-22',NULL,1,2);
INSERT INTO Person VALUES(23,'Rhea','Seehorn',NULL,NULL,'1972-05-12',NULL,1,1);
INSERT INTO Person VALUES(24,'Jonathan','Banks',NULL,NULL,'1947-01-31',NULL,1,2);

INSERT INTO Content VALUES(1,'Taxi Driver','A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence and sleaze fuels his urge for violent action by attempting to liberate a presidential campaign worker and an underage prostitute.','M/18',NULL,114);
INSERT INTO Content VALUES(2,'Pulp Fiction','The lives of two mob hitmen, a boxer, a gangster''s wife, and a pair of diner bandits intertwine in four tales of violence and redemption.','M/16',NULL,154);
INSERT INTO Content VALUES(3,'Clockwork Orange','In the future, a sadistic gang leader is imprisoned and volunteers for a conduct-aversion experiment, but it doesn''t go as planned.','M/16',NULL,136);
INSERT INTO Content VALUES(4,'The Big Lebowsky',NULL,'M/12',NULL,117);
INSERT INTO Content VALUES(5,'Trainspotting','Renton, deeply immersed in the Edinburgh drug scene, tries to clean up and get out, despite the allure of the drugs and influence of friends.','M/18',NULL,93);
INSERT INTO Content VALUES(6,'The Shining',NULL,'M/16',NULL,146);
INSERT INTO Content VALUES(7,'Pilot',NULL,'M/16',NULL,58);
INSERT INTO Content VALUES(8,'Cat''s in the bag...','After their first drug deal goes terribly wrong, Walt and Jesse are forced to deal with a corpse and a prisoner. Meanwhile, Skyler grows suspicious of Walt''s activities.','M/16',NULL,48);
INSERT INTO Content VALUES(9,'...and the bag''s in the river','As Jesse struggles to sell the meth he and Walter made, the chemistry teacher faces his own dilemmas, such as hiding his cancer from his wife and deciding what to do with Jesse''s prisoner Krazy-8.','M/16',NULL,48);
INSERT INTO Content VALUES(10,'Seven Thirty-Seven','Walt and Jesse realize how dire their situation is. They must come up with a plan to kill Tuco before Tuco kills them first.','M/16',NULL,51);
INSERT INTO Content VALUES(11,'Grilled','Walt''s disappearance is met with investigation by both his wife and Hank, as Tuco Salamanca intends to leave town with his kidnapped cooks.','M/16',NULL,49);
INSERT INTO Content VALUES(12,'No Más','Skyler goes through with her plans to divorce Walt. Jesse finishes rehab.','M/16',NULL,44);
INSERT INTO Content VALUES(13,'Caballo sin Nombre','Walter, Jr. is having a rough time accepting his parents'' separation. Jesse buys his old house from his parents. Meanwhile, two mysterious men have come into town looking for Walt.','M/16',NULL,48);
INSERT INTO Content VALUES(14,'Box Cutter','Walt and Jesse are held captive for Gus, after Gale''s death. Meanwhile, Skyler tries to find out what happened to Walt.','M/16',NULL,52);
INSERT INTO Content VALUES(15,'Live Free or Die','Now that Gus is dead, Walt, Jesse, and Mike work to cover their tracks. Skyler panics when Ted Beneke wakes up.','M/16',NULL,50);
INSERT INTO Content VALUES(16,'Madrigal','Walt and Jesse seek out an unlikely partner for a new business venture. The DEA follows up new leads in its investigation.','M/16',NULL,48);

INSERT INTO Movie VALUES(1,1976,28299999.999999999999,1900000.0);
INSERT INTO Movie VALUES(2,1994,213900000.0,8500000.0);
INSERT INTO Movie VALUES(3,1971,26600000.0,2200000.0);
INSERT INTO Movie VALUES(4,1998,46199999.999999999998,15000000.0);
INSERT INTO Movie VALUES(5,1996,NULL,NULL);
INSERT INTO Movie VALUES(6,1980,44400000.0,19000000.0);

INSERT INTO TVShow VALUES(1,'Breaking Bad','A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family''s future.','M/16',NULL,'false');

INSERT INTO Episode VALUES(7,1,1,1);
INSERT INTO Episode VALUES(8,2,1,1);
INSERT INTO Episode VALUES(9,3,1,1);
INSERT INTO Episode VALUES(10,1,2,1);
INSERT INTO Episode VALUES(11,2,2,1);
INSERT INTO Episode VALUES(12,1,3,1);
INSERT INTO Episode VALUES(13,2,3,1);
INSERT INTO Episode VALUES(14,1,4,1);
INSERT INTO Episode VALUES(15,1,5,1);
INSERT INTO Episode VALUES(16,2,5,1);

INSERT INTO ContentGenre VALUES(1,1);
INSERT INTO ContentGenre VALUES(1,2);
INSERT INTO ContentGenre VALUES(2,1);
INSERT INTO ContentGenre VALUES(2,2);
INSERT INTO ContentGenre VALUES(3,1);
INSERT INTO ContentGenre VALUES(3,2);
INSERT INTO ContentGenre VALUES(3,3);
INSERT INTO ContentGenre VALUES(4,4);
INSERT INTO ContentGenre VALUES(4,1);
INSERT INTO ContentGenre VALUES(5,2);
INSERT INTO ContentGenre VALUES(6,2);
INSERT INTO ContentGenre VALUES(6,5);
INSERT INTO ContentGenre VALUES(7,1);
INSERT INTO ContentGenre VALUES(7,2);
INSERT INTO ContentGenre VALUES(8,1);
INSERT INTO ContentGenre VALUES(8,2);
INSERT INTO ContentGenre VALUES(9,1);
INSERT INTO ContentGenre VALUES(9,2);
INSERT INTO ContentGenre VALUES(10,1);
INSERT INTO ContentGenre VALUES(10,2);
INSERT INTO ContentGenre VALUES(11,1);
INSERT INTO ContentGenre VALUES(11,2);
INSERT INTO ContentGenre VALUES(12,1);
INSERT INTO ContentGenre VALUES(12,2);
INSERT INTO ContentGenre VALUES(13,1);
INSERT INTO ContentGenre VALUES(13,2);
INSERT INTO ContentGenre VALUES(14,1);
INSERT INTO ContentGenre VALUES(14,2);
INSERT INTO ContentGenre VALUES(15,1);
INSERT INTO ContentGenre VALUES(15,2);
INSERT INTO ContentGenre VALUES(16,1);
INSERT INTO ContentGenre VALUES(16,2);

INSERT INTO Released VALUES(1,'1977-04-15',2);
INSERT INTO Released VALUES(1,'1976-03-22',8);
INSERT INTO Released VALUES(1,'1976-02-07',1);

INSERT INTO RolePersonContent VALUES(1,3,1);
INSERT INTO RolePersonContent VALUES(2,1,1);
INSERT INTO RolePersonContent VALUES(3,2,1);
INSERT INTO RolePersonContent VALUES(1,4,1);
INSERT INTO RolePersonContent VALUES(1,5,2);
INSERT INTO RolePersonContent VALUES(1,6,2);
INSERT INTO RolePersonContent VALUES(1,7,2);
INSERT INTO RolePersonContent VALUES(1,8,2);
INSERT INTO RolePersonContent VALUES(2,9,2);
INSERT INTO RolePersonContent VALUES(3,9,2);
INSERT INTO RolePersonContent VALUES(1,9,2);
INSERT INTO RolePersonContent VALUES(2,14,3);
INSERT INTO RolePersonContent VALUES(1,15,3);
INSERT INTO RolePersonContent VALUES(1,17,4);
INSERT INTO RolePersonContent VALUES(1,18,4);
INSERT INTO RolePersonContent VALUES(2,19,4);
INSERT INTO RolePersonContent VALUES(1,16,5);
INSERT INTO RolePersonContent VALUES(1,20,6);
INSERT INTO RolePersonContent VALUES(1,21,6);
INSERT INTO RolePersonContent VALUES(2,14,6);
INSERT INTO RolePersonContent VALUES(1,11,7);
INSERT INTO RolePersonContent VALUES(1,2,7);
INSERT INTO RolePersonContent VALUES(1,13,7);
INSERT INTO RolePersonContent VALUES(2,10,7);
INSERT INTO RolePersonContent VALUES(3,10,7);
INSERT INTO RolePersonContent VALUES(1,11,8);
INSERT INTO RolePersonContent VALUES(1,12,8);
INSERT INTO RolePersonContent VALUES(1,13,8);
INSERT INTO RolePersonContent VALUES(2,25,8);
INSERT INTO RolePersonContent VALUES(3,10,8);
INSERT INTO RolePersonContent VALUES(1,11,9);
INSERT INTO RolePersonContent VALUES(1,12,9);
INSERT INTO RolePersonContent VALUES(1,13,9);
INSERT INTO RolePersonContent VALUES(2,25,9);
INSERT INTO RolePersonContent VALUES(3,10,9);
INSERT INTO RolePersonContent VALUES(1,11,10);
INSERT INTO RolePersonContent VALUES(1,12,10);
INSERT INTO RolePersonContent VALUES(1,13,10);
INSERT INTO RolePersonContent VALUES(2,25,10);
INSERT INTO RolePersonContent VALUES(3,10,10);
INSERT INTO RolePersonContent VALUES(1,11,11);
INSERT INTO RolePersonContent VALUES(1,12,11);
INSERT INTO RolePersonContent VALUES(1,13,11);
INSERT INTO RolePersonContent VALUES(2,10,11);
INSERT INTO RolePersonContent VALUES(3,10,11);
INSERT INTO RolePersonContent VALUES(1,11,12);
INSERT INTO RolePersonContent VALUES(1,12,12);
INSERT INTO RolePersonContent VALUES(1,13,12);
INSERT INTO RolePersonContent VALUES(1,22,12);
INSERT INTO RolePersonContent VALUES(1,24,12);
INSERT INTO RolePersonContent VALUES(2,25,12);
INSERT INTO RolePersonContent VALUES(3,10,12);
INSERT INTO RolePersonContent VALUES(1,11,13);
INSERT INTO RolePersonContent VALUES(1,12,13);
INSERT INTO RolePersonContent VALUES(1,13,13);
INSERT INTO RolePersonContent VALUES(1,22,13);
INSERT INTO RolePersonContent VALUES(1,24,13);
INSERT INTO RolePersonContent VALUES(2,25,13);
INSERT INTO RolePersonContent VALUES(3,10,13);
INSERT INTO RolePersonContent VALUES(1,11,14);
INSERT INTO RolePersonContent VALUES(1,12,14);
INSERT INTO RolePersonContent VALUES(1,13,14);
INSERT INTO RolePersonContent VALUES(1,22,14);
INSERT INTO RolePersonContent VALUES(1,24,14);
INSERT INTO RolePersonContent VALUES(2,10,14);
INSERT INTO RolePersonContent VALUES(3,10,14);
INSERT INTO RolePersonContent VALUES(1,11,15);
INSERT INTO RolePersonContent VALUES(1,12,15);
INSERT INTO RolePersonContent VALUES(1,13,15);
INSERT INTO RolePersonContent VALUES(1,22,15);
INSERT INTO RolePersonContent VALUES(1,24,15);
INSERT INTO RolePersonContent VALUES(2,25,15);
INSERT INTO RolePersonContent VALUES(3,10,15);
INSERT INTO RolePersonContent VALUES(1,11,16);
INSERT INTO RolePersonContent VALUES(1,12,16);
INSERT INTO RolePersonContent VALUES(1,13,16);
INSERT INTO RolePersonContent VALUES(1,22,16);
INSERT INTO RolePersonContent VALUES(1,24,16);
INSERT INTO RolePersonContent VALUES(2,25,16);
INSERT INTO RolePersonContent VALUES(3,10,16);

