PRAGMA foreign_keys = ON;

INSERT INTO User VALUES(1,'up201706736@fe.up.pt','lpc');
INSERT INTO User VALUES(2,'up201705373@fe.up.pt','dhero');
INSERT INTO User VALUES(3,'up201706534@fe.up.pt','b670');
INSERT INTO User VALUES(4,'user4@hello.com','dlr4');
INSERT INTO User VALUES(5,'user5@hello.com','cdalhj');
INSERT INTO User VALUES(6,'user6@hello.com','yey');

INSERT INTO Country (id,name) VALUES(1,"United States of America");
INSERT INTO Country (id,name) VALUES(2,"Portugal");
INSERT INTO Country (id,name) VALUES(3,"Australia");
INSERT INTO Country (id,name) VALUES(4,"Italy");
INSERT INTO Country (id,name) VALUES(5,"England");
INSERT INTO Country (id,name) VALUES(6,"Scotland");
INSERT INTO Country (id,name) VALUES(7,"Germany");
INSERT INTO Country (id,name) VALUES(8,"Brazil");
INSERT INTO Country (id,name) VALUES(9,"Mexico");
INSERT INTO Country (id,name) VALUES(10,"France");
INSERT INTO Country (id,name) VALUES(11,"Canada");
INSERT INTO Country (id,name) VALUES(12,"Japan");
INSERT INTO Country (id,name) VALUES(13,"Angola");
INSERT INTO Country (id,name) VALUES(14,"Belgium");
INSERT INTO Country (id,name) VALUES(15,"South Africa");
INSERT INTO Country (id,name) VALUES(16,"Venezuela");
INSERT INTO Country (id,name) VALUES(17,"Egypt");
INSERT INTO Country (id,name) VALUES(18,"Jamaica");
INSERT INTO Country (id,name) VALUES(19,"Kazakhstan");
INSERT INTO Country (id,name) VALUES(20,"Spain");

INSERT INTO Gender VALUES(1,'Female');
INSERT INTO Gender VALUES(2,'Male');

INSERT INTO Role VALUES(1,'Actor');
INSERT INTO Role VALUES(2,'Director');
INSERT INTO Role VALUES(3,'Writer');
INSERT INTO Role VALUES(4,'Voice actor');

INSERT INTO Genre VALUES(1,'Crime','Films of this genre generally involve various aspects of crime and its detection.');
INSERT INTO Genre VALUES(2,'Drama','In film and television, drama is a genre of narrative fiction (or semi-fiction) intended to be more serious than humorous in tone.');
INSERT INTO Genre VALUES(3,'Science-fiction','Genre that uses speculative, fictional science-based depictions of phenomena that are not fully accepted by mainstream science.');
INSERT INTO Genre VALUES(4,'Comedy','Comedy is a genre of film in which the main emphasis is on humour.');
INSERT INTO Genre VALUES(5,'Horror','A horror film is a film that seeks to elicit fear.');
INSERT INTO Genre VALUES(6,'Animation','Animation is a method in which pictures are manipulated to appear as moving images.');

INSERT INTO Person VALUES(1,'Martin','Scorsese',NULL,'path/in/the/filesystem','1942-11-17',NULL,1,2);
INSERT INTO Person VALUES(2,'Paul','Schrader',NULL,'path/to/photo','1946-07-22',NULL,1,2);
INSERT INTO Person VALUES(3,'Robert','De Niro','One of the greatest actors of all time, Robert De Niro was born on August 17, 1943 in Manhattan, New York City, to artists Virginia (Admiral) and Robert De Niro Sr.','path/to/photo','1943-08-17',NULL,1,2);
INSERT INTO Person VALUES(4,'Jodie','Foster',NULL,'path/to/photo','1962-11-19',NULL,1,1);
INSERT INTO Person VALUES(5,'Uma','Thurman','Uma Karuna Thurman was born in Boston, Massachusetts, into a highly unorthodox and Eurocentric family.',NULL,'1970-04-29',NULL,1,1);
INSERT INTO Person VALUES(6,'Samuel','L. Jackson',NULL,'path/to/photo','1948-12-21',NULL,1,2);
INSERT INTO Person VALUES(7,'John','Travolta',NULL,'path/to/photo','1954-02-18',NULL,1,2);
INSERT INTO Person VALUES(8,'Maria','Medeiros','Maria de Medeiros is the oldest of three daughters by the pianist, maestro and composer António Vitorino D''Almeida and Maria Armanda Esteves.',NULL,'1965-08-19',NULL,2,1);
INSERT INTO Person VALUES(9,'Quentin','Tarantino','Quentin Jerome Tarantino was born in Knoxville, Tennessee. His father, Tony Tarantino, is an Italian-American actor and musician from New York, and his mother, Connie (McHugh), is a nurse from Tennessee','path/to/photo','1963-03-27',NULL,1,2);
INSERT INTO Person VALUES(10,'Vince','Gilligan','George Vincent Gilligan Jr. (born February 10, 1967) is an American writer, producer, and director.',NULL,'1967-02-10',NULL,1,2);
INSERT INTO Person VALUES(11,'Bryan','Cranston','Bryan Lee Cranston was born on March 7, 1956 in Hollywood, California, to Audrey Peggy Sell, a radio actress, and Joe Cranston, an actor and former amateur boxer.','path/to/photo','1956-03-07',NULL,1,2);
INSERT INTO Person VALUES(12,'Aaron','Paul',NULL,NULL,'1979-08-27',NULL,1,2);
INSERT INTO Person VALUES(13,'Anna','Gunn',NULL,'path/to/photo','1968-08-11',NULL,1,1);
INSERT INTO Person VALUES(14,'Stanley','Kubrick','Stanley Kubrick was born in Manhattan, New York City, to Sadie Gertrude (Perveler) and Jacob Leonard Kubrick, a physician.',NULL,'1928-07-26','1999-03-07',1,2);
INSERT INTO Person VALUES(15,'Malcolm','McDowell',NULL,'path/to/photo','1943-06-13',NULL,5,2);
INSERT INTO Person VALUES(16,'Ewan','McGregor',NULL,'path/to/photo','1971-03-31',NULL,6,2);
INSERT INTO Person VALUES(17,'Jeff','Bridges','Jeffrey Leon Bridges was born on December 4, 1949 in Los Angeles, California, the son of well-known film and TV star Lloyd Bridges and his long-time wife Dorothy Dean Bridges (née Simpson).','path/to/photo','1949-12-04',NULL,1,2);
INSERT INTO Person VALUES(18,'Steve','Buscemi','Steve Buscemi was born in Brooklyn, New York, to Dorothy (Wilson), a restaurant hostess, and John Buscemi, a sanitation worker.','path/to/photo','1957-12-13',NULL,1,2);
INSERT INTO Person VALUES(19,'Joel','Coen',NULL,NULL,'1954-11-29',NULL,1,2);
INSERT INTO Person VALUES(20,'Jack','Nicholson','Jack Nicholson, an American actor, producer, director and screenwriter, is a three-time Academy Award winner and twelve-time nominee.',NULL,'1937-04-22',NULL,1,2);
INSERT INTO Person VALUES(21,'Shelley','Duvall',NULL,'path/to/photo','1949-07-07',NULL,1,1);
INSERT INTO Person VALUES(22,'Bob','Odenkirk','Robert John Odenkirk was born in Berwyn, Illinois, to Barbara (Baier) and Walter Odenkirk, who worked in printing.','path/to/photo','1962-10-22',NULL,1,2);
INSERT INTO Person VALUES(23,'Rhea','Seehorn','Rhea Seehorn studied painting and drawing from a young age, following in the footsteps of her father and grandmother.',NULL,'1972-05-12',NULL,1,1);
INSERT INTO Person VALUES(24,'Jonathan','Banks','Versatile veteran character actor Jonathan Banks was born in Washington D.C in 1947. While growing up he always had an interest in acting and stage work, so decided to pursue a career in entertainment.','path/to/photo','1947-01-31',NULL,1,2);
INSERT INTO Person VALUES(25,'Adam','Bernstein',NULL,'path/to/photo','1960-05-07',NULL,1,2);
INSERT INTO Person VALUES(26,'Ricky','Gervais','Ricky Dene Gervais was born in a suburb of Reading, Berkshire, to Eva Sophia (House) and Lawrence Raymond Gervais, who was a hod carrier and labourer.','path/to/photo','1961-06-25',NULL,5,2);
INSERT INTO Person VALUES(27,'Tony','Way',NULL,NULL,'1978-11-07',NULL,5,2);
INSERT INTO Person VALUES(28,'Dan','Harmon','Dan Harmon was born on January 3, 1973 in Milwaukee, Wisconsin, USA. He is best known as the creator, writing, and producer for Community (2007) and Rick and Morty (2013). He also is known for writing and producing earlier works such as Computerman (2003), and Laser Fart (2004)',NULL,'1973-01-03',NULL,1,2);
INSERT INTO Person VALUES(29,'Justin','Roiland','Justin Roiland was born on February 21, 1980 in Stockton, California, USA as Mark Justin Roiland. He is an actor and producer, known for Rick e Morty (2013), The Most Extraordinary Space Investigations (2005) and 2 Girls, 1 Cup: The Show (2008).','path/to/photo','1980-02-21',NULL,1,2);
INSERT INTO Person VALUES(30,'Wesley','Archer','Wesley Archer was born on November 26, 1961 in Houston, Texas, USA as Wesley Meyer Archer. He is known for his work on Rick e Morty (2013), King of the Hill (1997) and Os Simpsons (1989).',NULL,'1961-11-26',NULL,1,2);
INSERT INTO Person VALUES(31,'John','Hodge','John Hodge was born in 1964 in Glasgow, Scotland. He is a writer and actor, known for Trainspotting (1996), T2 Trainspotting (2017) and Pequenos Crimes Entre Amigos (1994).',NULL,'1964-11-23',NULL,6,2);

INSERT INTO Content VALUES(1,'Taxi Driver','A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence and sleaze fuels his urge for violent action by attempting to liberate a presidential campaign worker and an underage prostitute.','M/18',NULL,114);
INSERT INTO Content VALUES(2,'Pulp Fiction','The lives of two mob hitmen, a boxer, a gangster''s wife, and a pair of diner bandits intertwine in four tales of violence and redemption.','M/16',NULL,154);
INSERT INTO Content VALUES(3,'Clockwork Orange','In the future, a sadistic gang leader is imprisoned and volunteers for a conduct-aversion experiment, but it doesn''t go as planned.','M/16',NULL,136);
INSERT INTO Content VALUES(4,'The Big Lebowsky',NULL,'M/12',NULL,117);
INSERT INTO Content VALUES(5,'Trainspotting','Renton, deeply immersed in the Edinburgh drug scene, tries to clean up and get out, despite the allure of the drugs and influence of friends.','M/18',NULL,93);
INSERT INTO Content VALUES(6,'The Shining',NULL,'M/16',NULL,146);
INSERT INTO Content VALUES(7,'Pilot',NULL,'M/16',NULL,58);
INSERT INTO Content VALUES(8,'Cat''s in the bag...','After their first drug deal goes terribly wrong, Walt and Jesse are forced to deal with a corpse and a prisoner. Meanwhile, Skyler grows suspicious of Walt''s activities.','M/16',NULL,48);
INSERT INTO Content VALUES(9,'...and the bag''s in the river','As Jesse struggles to sell the meth he and Walter made, the chemistry teacher faces his own dilemmas, such as hiding his cancer from his wife and deciding what to do with Jesse''s prisoner Krazy-8.','M/16',NULL,48);
INSERT INTO Content VALUES(10,'Seven Thirty-Seven','Walt and Jesse realize how dire their situation is. They must come up with a plan to kill Tuco before Tuco kills them first.','M/16',NULL,51);
INSERT INTO Content VALUES(11,'Grilled','Walt''s disappearance is met with investigation by both his wife and Hank, as Tuco Salamanca intends to leave town with his kidnapped cooks.','M/16',NULL,49);
INSERT INTO Content VALUES(12,'No Más','Skyler goes through with her plans to divorce Walt. Jesse finishes rehab.','M/16',NULL,44);
INSERT INTO Content VALUES(13,'Caballo sin Nombre','Walter, Jr. is having a rough time accepting his parents'' separation. Jesse buys his old house from his parents. Meanwhile, two mysterious men have come into town looking for Walt.','M/16',NULL,48);
INSERT INTO Content VALUES(14,'Box Cutter','Walt and Jesse are held captive for Gus, after Gale''s death. Meanwhile, Skyler tries to find out what happened to Walt.','M/16',NULL,52);
INSERT INTO Content VALUES(15,'Live Free or Die','Now that Gus is dead, Walt, Jesse, and Mike work to cover their tracks. Skyler panics when Ted Beneke wakes up.','M/16',NULL,50);
INSERT INTO Content VALUES(16,'Madrigal','Walt and Jesse seek out an unlikely partner for a new business venture. The DEA follows up new leads in its investigation.','M/16',NULL,48);
INSERT INTO Content VALUES(17,'Episode #1.1','Tony''s cantankerous funk - which he calls a superpower - is taking a toll on his co-workers. Meanwhile, a new writer starts at The Tambury Gazette. ',NULL,NULL,30);
INSERT INTO Content VALUES(18,'Episode #1.2','Thinking he has nothing to lose, Tony contemplates trying heroin. He babysits his nephew and starts to bond - just a bit - with Sandy.',NULL,NULL,31);
INSERT INTO Content VALUES(19,'Episode #1.3','Tony hires a sex worker - but it''s not what you think. A trip to the comedy club turns awkward. The nurse gives Tony a piece of her mind. ',NULL,NULL,29);
INSERT INTO Content VALUES(20,'Pilot','A sociopathic scientist drags his innocent grandson on dangerous inter-dimensional adventures.','M/16',NULL,22);
INSERT INTO Content VALUES(21,'A Rickle in Time','Having restarted time, Rick, Morty and Summer are in a quantum-uncertain state of existence.','M/16',NULL,23);
INSERT INTO Content VALUES(22,'The Rickshank Rickdemption','Rick, still in galactic prison, puts an intricate escape plan into action.','M/16',NULL,23);
INSERT INTO Content VALUES(23,'Rickmancing the Stone','With the kids dealing with their parents'' divorce, Rick takes them to a Mad Max-style universe where he tries to steal a green crystal from a group of scavengers.','M/16',NULL,22);
INSERT INTO Content VALUES(24,'Trumbo','In 1947, Dalton Trumbo was Hollywood''s top screenwriter, until he and other artists were jailed and blacklisted for their political beliefs.','M/16',NULL,124);


INSERT INTO Movie VALUES(1,1976,28299999.999999999999,1900000.0);
INSERT INTO Movie VALUES(2,1994,213900000.0,8500000.0);
INSERT INTO Movie VALUES(3,1971,26600000.0,2200000.0);
INSERT INTO Movie VALUES(4,1998,46199999.999999999998,15000000.0);
INSERT INTO Movie VALUES(5,1996,NULL,NULL);
INSERT INTO Movie VALUES(6,1980,44400000.0,19000000.0);
INSERT INTO Movie VALUES(24, 2015,15000000.0,12100000.0);

INSERT INTO TVShow VALUES(1,'Breaking Bad','A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family''s future.','M/16',NULL,'false');
INSERT INTO TVShow VALUES(2,'After Life','After Tony''s wife dies unexpectedly, his nice-guy persona is altered into an impulsive, devil-may-care attitude taking his old world by storm.',NULL,NULL,'true');
INSERT INTO TVShow VALUES(3,'Rick and Morty','An animated series that follows the exploits of a super scientist and his not-so-bright grandson.','M/16',NULL,'true');

INSERT INTO Episode VALUES(7,1,1,1);
INSERT INTO Episode VALUES(8,2,1,1);
INSERT INTO Episode VALUES(9,3,1,1);
INSERT INTO Episode VALUES(10,1,2,1);
INSERT INTO Episode VALUES(11,2,2,1);
INSERT INTO Episode VALUES(12,1,3,1);
INSERT INTO Episode VALUES(13,2,3,1);
INSERT INTO Episode VALUES(14,1,4,1);
INSERT INTO Episode VALUES(15,1,5,1);
INSERT INTO Episode VALUES(16,2,5,1);
INSERT INTO Episode VALUES(17,1,1,2);
INSERT INTO Episode VALUES(18,2,1,2);
INSERT INTO Episode VALUES(19,3,1,2);
INSERT INTO Episode VALUES(20,1,1,3);
INSERT INTO Episode VALUES(21,1,2,3);
INSERT INTO Episode VALUES(22,1,3,3);
INSERT INTO Episode VALUES(23,2,4,3);

INSERT INTO Creator VALUES(10,1);
INSERT INTO Creator VALUES(25,2);
INSERT INTO Creator VALUES(28,3);
INSERT INTO Creator VALUES(29,3);

INSERT INTO ContentGenre VALUES(1,1);
INSERT INTO ContentGenre VALUES(1,2);
INSERT INTO ContentGenre VALUES(2,1);
INSERT INTO ContentGenre VALUES(2,2);
INSERT INTO ContentGenre VALUES(3,1);
INSERT INTO ContentGenre VALUES(3,2);
INSERT INTO ContentGenre VALUES(3,3);
INSERT INTO ContentGenre VALUES(4,4);
INSERT INTO ContentGenre VALUES(4,1);
INSERT INTO ContentGenre VALUES(5,2);
INSERT INTO ContentGenre VALUES(6,2);
INSERT INTO ContentGenre VALUES(6,5);
INSERT INTO ContentGenre VALUES(7,1);
INSERT INTO ContentGenre VALUES(7,2);
INSERT INTO ContentGenre VALUES(8,1);
INSERT INTO ContentGenre VALUES(8,2);
INSERT INTO ContentGenre VALUES(9,1);
INSERT INTO ContentGenre VALUES(9,2);
INSERT INTO ContentGenre VALUES(10,1);
INSERT INTO ContentGenre VALUES(10,2);
INSERT INTO ContentGenre VALUES(11,1);
INSERT INTO ContentGenre VALUES(11,2);
INSERT INTO ContentGenre VALUES(12,1);
INSERT INTO ContentGenre VALUES(12,2);
INSERT INTO ContentGenre VALUES(13,1);
INSERT INTO ContentGenre VALUES(13,2);
INSERT INTO ContentGenre VALUES(14,1);
INSERT INTO ContentGenre VALUES(14,2);
INSERT INTO ContentGenre VALUES(15,1);
INSERT INTO ContentGenre VALUES(15,2);
INSERT INTO ContentGenre VALUES(16,1);
INSERT INTO ContentGenre VALUES(16,2);
INSERT INTO ContentGenre VALUES(17,2);
INSERT INTO ContentGenre VALUES(17,4);
INSERT INTO ContentGenre VALUES(18,2);
INSERT INTO ContentGenre VALUES(18,4);
INSERT INTO ContentGenre VALUES(19,2);
INSERT INTO ContentGenre VALUES(19,4);
INSERT INTO ContentGenre VALUES(20,4);
INSERT INTO ContentGenre VALUES(20,6);
INSERT INTO ContentGenre VALUES(21,4);
INSERT INTO ContentGenre VALUES(21,6);
INSERT INTO ContentGenre VALUES(22,4);
INSERT INTO ContentGenre VALUES(22,6);
INSERT INTO ContentGenre VALUES(23,4);
INSERT INTO ContentGenre VALUES(23,6);

INSERT INTO Released VALUES(1,'1977-04-15',2);
INSERT INTO Released VALUES(1,'1976-03-22',8);
INSERT INTO Released VALUES(1,'1976-02-07',1);
INSERT INTO Released VALUES(17,'2019-03-08',1);
INSERT INTO Released VALUES(17,'2019-03-08',7);
INSERT INTO Released VALUES(18,'2019-03-08',1);
INSERT INTO Released VALUES(18,'2019-03-08',7);
INSERT INTO Released VALUES(19,'2019-03-08',1);
INSERT INTO Released VALUES(19,'2019-03-08',7);
INSERT INTO Released VALUES(2,'1994-09-23',1);
INSERT INTO Released VALUES(2,'1994-11-25',2);
INSERT INTO Released VALUES(2,'1994-05-21',10);
INSERT INTO Released VALUES(3,'1971-12-19',1);
INSERT INTO Released VALUES(4,'1998-02-26',1);
INSERT INTO Released VALUES(4,'1998-10-30',2);
INSERT INTO Released VALUES(5,'1996-11-01',2);
INSERT INTO Released VALUES(6,'1980-11-20',2);
INSERT INTO Released VALUES(7,'2008-01-20',1);
INSERT INTO Released VALUES(8,'2008-01-27',1);
INSERT INTO Released VALUES(9,'2008-02-10',1);
INSERT INTO Released VALUES(10,'2009-03-08',1);
INSERT INTO Released VALUES(11,'2009-03-15',1);
INSERT INTO Released VALUES(12,'2010-03-21',1);
INSERT INTO Released VALUES(13,'2010-03-28',1);
INSERT INTO Released VALUES(14,'2011-07-17',1);
INSERT INTO Released VALUES(15,'2012-07-15',1);
INSERT INTO Released VALUES(16,'2012-07-22',1);
INSERT INTO Released VALUES(20,'2013-12-02',1);
INSERT INTO Released VALUES(21,'2015-07-26',1);
INSERT INTO Released VALUES(22,'2017-04-01',1);
INSERT INTO Released VALUES(23,'2017-07-30',1);

INSERT INTO RolePersonContent VALUES(1,3,1);
INSERT INTO RolePersonContent VALUES(2,1,1);
INSERT INTO RolePersonContent VALUES(3,2,1);
INSERT INTO RolePersonContent VALUES(1,4,1);
INSERT INTO RolePersonContent VALUES(1,5,2);
INSERT INTO RolePersonContent VALUES(1,6,2);
INSERT INTO RolePersonContent VALUES(1,7,2);
INSERT INTO RolePersonContent VALUES(1,8,2);
INSERT INTO RolePersonContent VALUES(2,9,2);
INSERT INTO RolePersonContent VALUES(3,9,2);
INSERT INTO RolePersonContent VALUES(1,9,2);
INSERT INTO RolePersonContent VALUES(2,14,3);
INSERT INTO RolePersonContent VALUES(1,15,3);
INSERT INTO RolePersonContent VALUES(1,17,4);
INSERT INTO RolePersonContent VALUES(1,18,4);
INSERT INTO RolePersonContent VALUES(2,19,4);
INSERT INTO RolePersonContent VALUES(1,16,5);
INSERT INTO RolePersonContent VALUES(1,20,6);
INSERT INTO RolePersonContent VALUES(1,21,6);
INSERT INTO RolePersonContent VALUES(2,14,6);
INSERT INTO RolePersonContent VALUES(1,11,7);
INSERT INTO RolePersonContent VALUES(1,2,7);
INSERT INTO RolePersonContent VALUES(1,13,7);
INSERT INTO RolePersonContent VALUES(2,10,7);
INSERT INTO RolePersonContent VALUES(3,10,7);
INSERT INTO RolePersonContent VALUES(1,11,8);
INSERT INTO RolePersonContent VALUES(1,12,8);
INSERT INTO RolePersonContent VALUES(1,13,8);
INSERT INTO RolePersonContent VALUES(2,25,8);
INSERT INTO RolePersonContent VALUES(3,10,8);
INSERT INTO RolePersonContent VALUES(1,11,9);
INSERT INTO RolePersonContent VALUES(1,12,9);
INSERT INTO RolePersonContent VALUES(1,13,9);
INSERT INTO RolePersonContent VALUES(2,25,9);
INSERT INTO RolePersonContent VALUES(3,10,9);
INSERT INTO RolePersonContent VALUES(1,11,10);
INSERT INTO RolePersonContent VALUES(1,12,10);
INSERT INTO RolePersonContent VALUES(1,13,10);
INSERT INTO RolePersonContent VALUES(2,25,10);
INSERT INTO RolePersonContent VALUES(3,10,10);
INSERT INTO RolePersonContent VALUES(1,11,11);
INSERT INTO RolePersonContent VALUES(1,12,11);
INSERT INTO RolePersonContent VALUES(1,13,11);
INSERT INTO RolePersonContent VALUES(2,10,11);
INSERT INTO RolePersonContent VALUES(3,10,11);
INSERT INTO RolePersonContent VALUES(1,11,12);
INSERT INTO RolePersonContent VALUES(1,12,12);
INSERT INTO RolePersonContent VALUES(1,13,12);
INSERT INTO RolePersonContent VALUES(1,22,12);
INSERT INTO RolePersonContent VALUES(1,24,12);
INSERT INTO RolePersonContent VALUES(2,25,12);
INSERT INTO RolePersonContent VALUES(3,10,12);
INSERT INTO RolePersonContent VALUES(1,11,13);
INSERT INTO RolePersonContent VALUES(1,12,13);
INSERT INTO RolePersonContent VALUES(1,13,13);
INSERT INTO RolePersonContent VALUES(1,22,13);
INSERT INTO RolePersonContent VALUES(1,24,13);
INSERT INTO RolePersonContent VALUES(2,25,13);
INSERT INTO RolePersonContent VALUES(3,10,13);
INSERT INTO RolePersonContent VALUES(1,11,14);
INSERT INTO RolePersonContent VALUES(1,12,14);
INSERT INTO RolePersonContent VALUES(1,13,14);
INSERT INTO RolePersonContent VALUES(1,22,14);
INSERT INTO RolePersonContent VALUES(1,24,14);
INSERT INTO RolePersonContent VALUES(2,10,14);
INSERT INTO RolePersonContent VALUES(3,10,14);
INSERT INTO RolePersonContent VALUES(1,11,15);
INSERT INTO RolePersonContent VALUES(1,12,15);
INSERT INTO RolePersonContent VALUES(1,13,15);
INSERT INTO RolePersonContent VALUES(1,22,15);
INSERT INTO RolePersonContent VALUES(1,24,15);
INSERT INTO RolePersonContent VALUES(2,25,15);
INSERT INTO RolePersonContent VALUES(3,10,15);
INSERT INTO RolePersonContent VALUES(1,11,16);
INSERT INTO RolePersonContent VALUES(1,12,16);
INSERT INTO RolePersonContent VALUES(1,13,16);
INSERT INTO RolePersonContent VALUES(1,22,16);
INSERT INTO RolePersonContent VALUES(1,24,16);
INSERT INTO RolePersonContent VALUES(2,25,16);
INSERT INTO RolePersonContent VALUES(3,10,16);
INSERT INTO RolePersonContent VALUES(1,26,17);
INSERT INTO RolePersonContent VALUES(1,27,17);
INSERT INTO RolePersonContent VALUES(2,26,17);
INSERT INTO RolePersonContent VALUES(3,26,17);
INSERT INTO RolePersonContent VALUES(1,26,18);
INSERT INTO RolePersonContent VALUES(1,27,18);
INSERT INTO RolePersonContent VALUES(2,26,18);
INSERT INTO RolePersonContent VALUES(3,26,18);
INSERT INTO RolePersonContent VALUES(1,26,19);
INSERT INTO RolePersonContent VALUES(1,27,19);
INSERT INTO RolePersonContent VALUES(2,26,19);
INSERT INTO RolePersonContent VALUES(3,26,19);
INSERT INTO RolePersonContent VALUES(2,29,20);
INSERT INTO RolePersonContent VALUES(3,29,20);
INSERT INTO RolePersonContent VALUES(3,28,20);
INSERT INTO RolePersonContent VALUES(4,29,20);
INSERT INTO RolePersonContent VALUES(2,30,21);
INSERT INTO RolePersonContent VALUES(3,29,21);
INSERT INTO RolePersonContent VALUES(3,28,21);
INSERT INTO RolePersonContent VALUES(4,29,21);
INSERT INTO RolePersonContent VALUES(2,30,22);
INSERT INTO RolePersonContent VALUES(3,29,22);
INSERT INTO RolePersonContent VALUES(3,8,22);
INSERT INTO RolePersonContent VALUES(4,29,22);
INSERT INTO RolePersonContent VALUES(2,29,23);
INSERT INTO RolePersonContent VALUES(3,29,23);
INSERT INTO RolePersonContent VALUES(3,28,23);
INSERT INTO RolePersonContent VALUES(4,29,23);

INSERT INTO ContentReview VALUES(1,3,10, 'A classic everyone should watch.');
INSERT INTO ContentReview VALUES(1,2,2, 'This movie is very boring. The acting seems forced and the movie follows a very cliche path.');
INSERT INTO ContentReview VALUES(1,1,4, 'Come on! A masterpiece? I think not.');
INSERT INTO ContentReview VALUES(2,3,6, 'The film was very cool, but the narrative was not linear and hard to follow.');
INSERT INTO ContentReview VALUES(2,2,5, 'A bit too bloody for my taste. Samuel L. Jackson was wonderful as always.');
INSERT INTO ContentReview VALUES(2,1,10, 'A masterpiece! A brilliant movie by the wonderful Quentin Tarantino. Would recommend and would watch again.');
INSERT INTO ContentReview VALUES(3,3,10, 'A very interesting movie that makes you think. Every actors performance was on point!');
INSERT INTO ContentReview VALUES(3,2,10, 'The trailer was misleading. Still, a nice movie.');
INSERT INTO ContentReview VALUES(3,1,6, 'I could not understand the movie when I saw it in the movie theater. Watched it again last night, still didnt understand. Would not recomend.');
INSERT INTO ContentReview VALUES(4,3,6, 'I liked the movie. Still, I think some of the moments seemed forced (maybe due to the actors inexperience).');
INSERT INTO ContentReview VALUES(4,2,10, 'Do yourself a favour and watch this movie if you havent already. Hell, even if youve already seen in, go watch it again!');
INSERT INTO ContentReview VALUES(4,1,9, 'A breath of fresh air! I could not think of a better blend between crime and comedy.');
INSERT INTO ContentReview VALUES(5,3,7, 'This movie makes you think in a way you havent thought before.');
INSERT INTO ContentReview VALUES(5,2,3, 'Honestly, i dont see the appeal of this movie.');
INSERT INTO ContentReview VALUES(5,1,8, 'If you dont understand the hidden meaning of this movie, go watch it again.');
INSERT INTO ContentReview VALUES(6,3,9, 'Stephen King is and always will be the king of terror.');
INSERT INTO ContentReview VALUES(6,2,5, 'I have mixed feelings about this movie. I mean, its, but it doesnt do much justice to the stephen king novel.');
INSERT INTO ContentReview VALUES(6,1,8, 'This movie aims to scare you in a more intellegent way than the average jump-scare-film and it succeeds.');
INSERT INTO ContentReview VALUES(7,3,8, 'The start to the legendary drama series. It starts slow but by the end you will be surely be begging for more.');
INSERT INTO ContentReview VALUES(14,1,5, 'This episode feels more like a "filler". Still a brilliant performance by Bryan Cranston');

INSERT INTO TVShowReview VALUES(1,3,9, 'One of the best tv series of all time. If you like drama this is the series to watch.');
INSERT INTO TVShowReview VALUES(1,2,2, 'I caught my son watching this. Drug related content should not be shown on TV');
INSERT INTO TVShowReview VALUES(1,1,7, 'It is a cool show but towards the end it feels kinda repetitive.');

INSERT INTO Watchlist VALUES(3,1);
INSERT INTO Watchlist VALUES(5,1);
INSERT INTO Watchlist VALUES(6,1);
INSERT INTO Watchlist VALUES(7,1);
INSERT INTO Watchlist VALUES(15,1);
INSERT INTO Watchlist VALUES(1,2);
INSERT INTO Watchlist VALUES(7,2);
INSERT INTO Watchlist VALUES(6,2);
INSERT INTO Watchlist VALUES(8,2);
INSERT INTO Watchlist VALUES(12,2);
INSERT INTO Watchlist VALUES(4,3);
INSERT INTO Watchlist VALUES(7,3);
INSERT INTO Watchlist VALUES(1,3);
INSERT INTO Watchlist VALUES(3,3);
INSERT INTO Watchlist VALUES(10,3);

INSERT INTO AwardName VALUES(1,'Golden Globe');
INSERT INTO AwardName VALUES(2,'Primetime Emmy');
INSERT INTO AwardName VALUES(3,'Screen Actors Guild');
INSERT INTO AwardName VALUES(4,'Oscar');
INSERT INTO AwardName VALUES(5,'British Academy Film Awards');
INSERT INTO AwardName VALUES(6,'Cannes Film Festival');
INSERT INTO AwardName VALUES(7, 'Broadcast Film Critics Association Awards');

INSERT INTO Award VALUES(1,'Best Television Series - Drama',1);
INSERT INTO Award VALUES(2,'Best Actor in a Television Series - Drama ',1);
INSERT INTO Award VALUES(3,'Outstanding Performance by a Male Actor in a Drama Series',3);
INSERT INTO Award VALUES(4,'Outstanding Performance by an Ensemble in a Drama Series',3);
INSERT INTO Award VALUES(5,'Outstanding Lead Actor in a Drama Series',2);
INSERT INTO Award VALUES(6,'Outstanding Drama Series',2);
INSERT INTO Award VALUES(7,'Outstanding Supporting Actress in a Drama Series',2);
INSERT INTO Award VALUES(8,'Outstanding Supporting Actor in a Drama Series',2);
INSERT INTO Award VALUES(9,'Best Writing, Screenplay Written Directly for the Screen',4);
INSERT INTO Award VALUES(10,'Best Screenplay - Motion Picture',1);
INSERT INTO Award VALUES(11,'Best Actor in a Supporting Role',1);
INSERT INTO Award VALUES(12,'Best Screenplay - Original',5);
INSERT INTO Award VALUES(13,'Best Screenplay - Adapted',5);
INSERT INTO Award VALUES(14,'Palme d''Or',6);
INSERT INTO Award VALUES(15, 'Outstanding Animated Program',2);
INSERT INTO Award VALUES(16, 'Best Actor',7);

INSERT INTO TVAward VALUES(2014,1,1,NULL);
INSERT INTO TVAward VALUES(2014,2,1,11);
INSERT INTO TVAward VALUES(2014,3,1,11);
INSERT INTO TVAward VALUES(2014,4,1,NULL);
INSERT INTO TVAward VALUES(2014,5,1,11);
INSERT INTO TVAward VALUES(2014,6,1,NULL);
INSERT INTO TVAward VALUES(2014,7,1,13);
INSERT INTO TVAward VALUES(2014,8,1,12);
INSERT INTO TVAward VALUES(2018,15,3,NULL);

INSERT INTO MovieAward VALUES(1995,9,2,9);
INSERT INTO MovieAward VALUES(1995,10,2,9);
INSERT INTO MovieAward VALUES(1995,11,2,6);
INSERT INTO MovieAward VALUES(1995,12,2,9);
INSERT INTO MovieAward VALUES(1996,13,5,31);
INSERT INTO MovieAward VALUES(1976,14,1,1);
INSERT INTO MovieAward VALUES(2016,16,24,11);